#!/usr/bin/env bash
# Smoke tests for the built pipe image, run both in CI and locally:
#   bash test/smoke.sh gocov/upload-pipe:ci
# Offline cases always run; the final case does a real upload to the
# hosted service and only runs when $GOCOV_TOKEN is set (CI dogfooding,
# uses the selftest coverage profile generated by the previous step).
set -euo pipefail

IMG=${1:?usage: smoke.sh <image>}
cd "$(dirname "$0")/.."

t() { echo "--- $1"; }

t "missing TOKEN fails"
out=$(docker run --rm -e FILES=coverage.out "$IMG" 2>&1) && { echo "expected exit 1"; exit 1; }
grep -q "TOKEN is required" <<<"$out"

t "missing TOKEN with FAIL_ON_ERROR=false succeeds with a warning"
out=$(docker run --rm -e FILES=coverage.out -e FAIL_ON_ERROR=false "$IMG" 2>&1)
grep -q "WARNING: TOKEN is required" <<<"$out"

t "no matching files fails"
out=$(docker run --rm -e FILES='nope-*.out' -e TOKEN=dummy "$IMG" 2>&1) && { echo "expected exit 1"; exit 1; }
grep -q "no coverage files matched" <<<"$out"

t "glob expansion finds files (upload fails on the dummy token, not on matching)"
dir=$(mktemp -d)
trap 'rm -rf "$dir"' EXIT
printf 'mode: atomic\n' >"$dir/a.out"
printf 'mode: atomic\n' >"$dir/b.out"
out=$(docker run --rm -e FILES='*.out' -e TOKEN=dummy -e SERVER=http://localhost:9 \
  -v "$dir":/work -w /work "$IMG" 2>&1) && { echo "expected exit 1"; exit 1; }
grep -q "uploading a.out" <<<"$out"
grep -q "uploading b.out" <<<"$out"
grep -q "2 of 2 upload(s) failed" <<<"$out"

if [ -n "${GOCOV_TOKEN:-}" ]; then
  t "dogfood: real upload of selftest coverage"
  docker run --rm -e FILES=selftest/coverage.out -e TOKEN="$GOCOV_TOKEN" \
    -e BITBUCKET_REPO_FULL_NAME -e BITBUCKET_COMMIT -e BITBUCKET_BRANCH -e BITBUCKET_PR_ID \
    -v "$PWD":/work -w /work "$IMG"
else
  t "dogfood upload skipped: GOCOV_TOKEN not set"
fi

echo "smoke tests passed"
